title: Aditya Barman
logo: docs/assets/Aditya-Barman_Vintage-image.png
description: Graduate Student (Computational Quantum Chemistry), Weizmann Institute of Science 
#show_downloads: true
theme: jekyll-theme-Hacker
